@domain = http://localhost:8099/
@jsonContentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlMzE4MDAxOTg2OTU4ZDNjMTAyZTIwIiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjA4ODAwNzc2fQ.D2cdQELNoi4jMY5HopYj9b4mqK7-_kIK7I5So6Dt5vU

### login
POST {{domain}}auth/login
Content-Type: {{jsonContentType}}

{
  "account": "admin",
  "password": "admin123"
}

### register account
POST {{domain}}user/register
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "account": "edmond",
  "password": "edmond123"
}