@domain = http://localhost:8099/
# @domain = https://butterfly-service.teraui.com/
# @domain = http://172.105.238.45:8099/
@jsonContentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlMzE4MDAxOTg2OTU4ZDNjMTAyZTIwIiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjA4ODAwNzc2fQ.D2cdQELNoi4jMY5HopYj9b4mqK7-_kIK7I5So6Dt5vU

### login
POST {{domain}}auth/login
Content-Type: {{jsonContentType}}

{
  "account": "admin",
  "password": "admin123"
}

### register account
POST {{domain}}user/register
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "account": "admin",
  "password": "admin123"
}

### getToken 
POST {{domain}}auth/token
Content-Type: {{jsonContentType}}

{
  "clientId": "ZWRtb25kOmdvb2RndXk=",
  "bedNo": "A9908",
  "language": "tw"
}

### sendAnswer
POST {{domain}}answer
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "bedNo": "A9908",
  "language": "tw",
  "answers": [ 1, 1, 1, 0, 0]
}

### getAllAnswer
GET {{domain}}report
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### get visit report
GET {{domain}}visit/report?startDate=2021/05/1&endDate=2021/05/10
Content-Type: {{jsonContentType}}

### add visitor
POST {{domain}}visit/visit
Content-Type: {{jsonContentType}}
